### ISSUE TITLE
Type the Coin Name

### ISSUE THREAD

**Issue by nafees00alam** [Samdurp/Binance-Pump-and-Dump-Bot#1]
Can there be an option where the user can enter the coin name?

**Comment by Samdurp** [comment]
There is an option to do this actually!

All you need to do is open the main.py file in your favorite IDE/text editor and change the "useOutputTxt" variable on line 14 to 0 instead of 1. Then during runtime of the script, it will ask the user to enter the coin they are buying. 

If you instead wish to change the coin you are paying with, you would have to modify the variable "payCoin" on line 173 from 'BTC' to your coin of choice, like 'ETH' or 'XLM'.

Hope this helps!!
